### ISSUE TITLE
[REQUEST] Function to use AI to scan images to Remove them if they are Catgirls

### ISSUE THREAD

**Issue by ferociouskyle** [refekt/Huskers-Discord-Bot#177]
**Is your feature request related to a problem? Please describe.**
Yes.. Too many cat girls being posted. We need to train AI to remove them.

**Describe the solution you'd like**
Solution #1: Remove them through an AI that looks for cats. 
Solution #2: Give me rights to remove photos so I can stop this nonsense.  

**Describe alternatives you've considered**
Leaving the server, or reporting the posts. 

**Additional context**
I got this under control. Thanks.

**Comment by NotaVirusClick** [comment]
Has this happened yet?  It would solve loads of frustration that I experience.

**Comment by MartyChonks** [comment]
:fiercecosmo:
