### ISSUE TITLE
[REQUEST] 69 Hours

### ISSUE THREAD

**Issue by NotaVirusClick** [refekt/Huskers-Discord-Bot#194]
Per Nishi

feature request: when countdown reaches 2 days 21 hours, rhulebot pipes up and says 69 hours to kickoff motherfuckers

Per mick:
Could you automate the daily reminder too. Don’t listen to Marty , he loves it

**Comment by refekt** [comment]
Only doing the second half

**Comment by NotaVirusClick** [comment]
What a crock of shit
